// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY8zvIkP55QX4GSDlAM_9YOcKyffT_6IA',
    appId: '1:562778833000:web:4a647b58afb5a0130dbbdd',
    messagingSenderId: '562778833000',
    projectId: 'life-os-2365d',
    authDomain: 'life-os-2365d.firebaseapp.com',
    storageBucket: 'life-os-2365d.firebasestorage.app',
    measurementId: 'G-E0VYDNWM27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrzqLcEooak7NrjqS6Fa6pRwYU3AZhQNA',
    appId: '1:562778833000:android:793c80aa36ac2b2f0dbbdd',
    messagingSenderId: '562778833000',
    projectId: 'life-os-2365d',
    storageBucket: 'life-os-2365d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJbC59fvp0W8MYSvJQ8e-B6mRq1IoPUoc',
    appId: '1:562778833000:ios:7fc7506b5be4f60c0dbbdd',
    messagingSenderId: '562778833000',
    projectId: 'life-os-2365d',
    storageBucket: 'life-os-2365d.firebasestorage.app',
    iosBundleId: 'com.example.lifeOs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJbC59fvp0W8MYSvJQ8e-B6mRq1IoPUoc',
    appId: '1:562778833000:ios:7fc7506b5be4f60c0dbbdd',
    messagingSenderId: '562778833000',
    projectId: 'life-os-2365d',
    storageBucket: 'life-os-2365d.firebasestorage.app',
    iosBundleId: 'com.example.lifeOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY8zvIkP55QX4GSDlAM_9YOcKyffT_6IA',
    appId: '1:562778833000:web:744ffeb2e2b1983b0dbbdd',
    messagingSenderId: '562778833000',
    projectId: 'life-os-2365d',
    authDomain: 'life-os-2365d.firebaseapp.com',
    storageBucket: 'life-os-2365d.firebasestorage.app',
    measurementId: 'G-TGD894CDTZ',
  );
}
